import * as sql from '../models/consultas.js'

// POST ingreso
export const getCredencialesGoogle = (req, res) => sql.verificarPertenencia(req.body.email)
  .then((data) => res.status(200).json(data))
  .catch((error) => res.status(500).json({ error: error.message })
  )
export const postTarea = (req, res) => sql.verificarPertenencia(req.body.email)
  .then((data) => res.status(200).json(data))
  .catch((error) => res.status(500).json({ error: error.message })
  )
// modificar NNA
export const modificarNna = (req, res) => sql.putNnj(req.body)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const postResumen = (req, res) => sql.addAnalisis(req.body.id, req.body.date, req.body.resumen, req.body.url)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
// GET
export const getDatosCredencial = async (req, res) => await sql.buscarDatosProfesional(req.user.email)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const getLogro = async (req, res) => await sql.logroPorId(req.query.id)
  .then((data) => res.status(200).json(data))
  .catch((error) => res.status(500).json(error)
  )
export const getProfesionales = async (req, res) => await sql.getProfesionales(req.query.id)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const getPro = async (req, res) => await sql.buscarDatosProfesional(req.user.email)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const getInforme = async (req, res) => await sql.getDataNna(req.query.id)
  .then((data) => res.status(200).json(data))
  .catch((error) => res.status(500).json(error)
  )
export const getListas = async (req, res) => await sql.getTablas()
  .then((data) => res.status(200).json(data))
  .catch((error) => res.status(500).json(error)
  )
export const logros = (req, res) => sql.getTodoLogros(req.query.id)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const getNna = (req, res) => sql.getNnj(req.query.id)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )

// PUT
export const putNna = (req, res) => sql.modificarNnj(req.body)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const putDato = (req, res) => sql.modificarDatos(req.body)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const putAdulto = (req, res) => sql.modificarDatosAdulto(req.body)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const putInforme = (req, res) => sql.checkInforme(req.body.id)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const putLista = (req, res) => sql.changeAdult(req.body)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const putProrroga = (req, res) => sql.insertProrroga(req.body.date, req.body.id)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
// POST
export const postNna = (req, res) => sql.insertNnj(req.body.data)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const postLogro = (req, res) => sql.addLogro(req.body)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const postAdulto = (req, res) => sql.insertAdulto(req.body.data)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )

// DELETE
export const deleteNna = (req, res) => sql.deleteNna(req.body.selectId)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
export const deleteLogro = (req, res) => sql.borrarLogro(req.query.id)
  .then((result) => res.status(200).json(result))
  .catch((error) => res.status(500).json(error)
  )
